Vagrant.configure("2") do |config|
  
  ## Choose your base box
  config.vm.box = "geerlingguy/centos7"

  # This is Ben trying to figure out Vagrant, and modify what Patrick has already done...
  config.vm.define "masterless_minion" do |masterless_minion|
    #masterless_minion.vm.network "public_network"
    # use the below config if you don't want to forward ports
    config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet0'
    # instead I will just forward 80 via 8080
    # config.vm.network "forwarded_port", guest: 8080, host: 8080

    ### Mount Salt file root
    masterless_minion.vm.synced_folder "states/", "/srv/salt/states/"
    masterless_minion.vm.synced_folder "~/git/chg-salt/states/", "/srv/salt/states/dev/"
    masterless_minion.vm.synced_folder "pillars/", "/srv/salt/pillars/"
    #masterless_minion.vm.synced_folder "formulae/", "/srv/salt/formulae/"
    masterless_minion.vm.synced_folder "configs/", "/srv/salt/configs/"
    
    masterless_minion.vm.provision "shell", inline: <<-EOF
      # Disable IPv6
      echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf
      /sbin/sysctl -p

      # Disable Fastest Mirror YUM plugin
      sed -i 's/enabled=1/enabled=0/' /etc/yum/pluginconf.d/fastestmirror.conf
      
      # Install EPEL repo
      #yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      # centos has this already in their repo, so...
      yum -y install epel-release
      
      # Install requisites for Salt as well some generic useful packages
      yum install -y python-pygit2 libgit2 git man-pages nano telnet bind-utils screen lsof vim-enhanced wget bash-completion bash-completion-extras
      
      # Preload Stash/Bitbucket's public SSH key
      ssh -o "StrictHostKeyChecking no" -o PasswordAuthentication=no -p 7999 ops.chgit.com
      
      # Bug in FIPS mode, https://github.com/Legrandin/pycryptodome/issues/64, https://repo.saltstack.com/2016.11.html#rhel
      # Install Salt repo
      yum install -y https://repo.saltstack.com/yum/redhat/salt-repo-2016.11-2.el7.noarch.rpm
      
      # Expire YUM cache
      yum clean expire-cache
      
      # Install Salt
      yum install -y salt salt-minion-0:2016.11.9-2.el7.noarch
      
      # Move default Salt Minion config file out of way
      mv /etc/salt/minion /etc/salt/minion.stock
      
      # Link new Salt Minion config to where Salt will look for it
      ln -s /srv/salt/configs/minion.config /etc/salt/minion
      
      # Set local hostname
      hostnamectl set-hostname masterless_minion.localdev
      
      # Set Salt Minion to start at reboot
      systemctl enable salt-minion.service

      # Start Salt Minion service
      systemctl start salt-minion.service

      # Set some local Salt grains
      salt-call grains.set env dev
      salt-call grains.append roles localdev
      salt-call mine.update
      EOF

    ### Provision masterless_minion via Salt
    #masterless_minion.vm.provision :salt do |salt|
    #  salt.masterless = true
    #  salt.minion_config = "configs/masterless_minion"
    #  salt.run_highstate = false
    #  salt.install_type = "stable"
    #end

    # Some states needs more memory or CPU to run the apps. Uncomment below if needed.
    masterless_minion.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "1"]
    end
  end

end
