Vagrant.configure("2") do |config|

  ## I may forget - the intent of this Vagrantfile is to set up a Salt master
	# responding to minions on the supplied IP address
	# I need to figure out how to make the minions check in to the master and get the master to save
	# the keys. or, make the master auto-accept all keys :)	
  ## Choose your base box
  config.vm.box = "geerlingguy/centos7"

  config.vm.define "master" do |master|
    ## Connect to host's network
    master.vm.network "private_network", ip: "192.168.221.10"
    
    ## Present guest network ports to host's network
    #master.vm.network "forwarded_port", guest: 4505, host: 4505, protocol: "tcp"
    #master.vm.network "forwarded_port", guest: 4506, host: 4506, protocol: "tcp"
    
    ## Mount Salt file root
    master.vm.synced_folder "states/", "/srv/salt/states/"
    master.vm.synced_folder "pillar/", "/srv/salt/pillar/"
    master.vm.synced_folder "reactor/", "/srv/salt/reactor/"
    #master.vm.synced_folder "~/Documents/git/chg/salt/states/", "/srv/salt/states/"
    #master.vm.synced_folder "~/Documents/git/chg/salt/pillars/", "/srv/salt/pillars/"
    #master.vm.synced_folder "formulae/", "/srv/salt/formulae/"
    #master.vm.synced_folder "configs/", "/srv/salt/configs/"
    
    ## If connected to public_network, uncomment this block to automatically install Salt
    master.vm.provision "shell", inline: <<-EOF
        # Disable IPv6
        echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf
        /sbin/sysctl -p
        
        sed -i 's/enabled=1/enabled=0/' /etc/yum/pluginconf.d/fastestmirror.conf
        yum -y install epel-release
        yum -y install wget screen rsync vim-enhanced bind-utils net-tools bash-completion bash-completion-extras

        # Install Salt repo
        yum install -y https://repo.saltstack.com/yum/redhat/salt-repo-2016.11-2.el7.noarch.rpm

        # Expire YUM cache
        yum clean expire-cache

        # Install Salt
        yum install -y salt salt-0:2016.11.9-2.el7.noarch salt-cloud-0:2016.11.9-2.el7.noarch salt-master-0:2016.11.9-2.el7.noarch pyOpenSSL salt-api

        # install salt config files for master
        cat /vagrant/etc/master > /etc/salt/master

        # Set local hostname
        hostnamectl set-hostname master.localdev

        # configure minion
        cat /vagrant/etc/minion > /etc/salt/minion

        # start minion
        systemctl enable salt-minion
        systemctl start salt-minion

        # generate SSL cert for API
        salt-call --local tls.create_self_signed_cert

        # set the vagrant user's password
        echo r0ck0n | passwd --stdin vagrant

        # start salt-api
        systemctl enable salt-api
        systemctl start salt-api

        # Set Salt Master to start at reboot
        systemctl enable salt-master.service

        # Start Salt Minion service
        systemctl start salt-master.service

        # Set some local Salt grains
        #salt-call grains.set env dev
        #salt-call grains.append roles localdev

      EOF
    
    # The master MAY need more CPU or memory if you can provide it - leaving this here for reference.
    master.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "1"]
    end
  
  end

(1..3).each do |i|
  config.vm.define "minion#{i}" do |node|
    node.vm.network "private_network", ip: "192.168.221.10#{i}"
    node.vm.provision "shell", inline: <<-EOF
      # some prep work
      # Disable IPv6
      echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf
      /sbin/sysctl -p
      
      sed -i 's/enabled=1/enabled=0/' /etc/yum/pluginconf.d/fastestmirror.conf
      yum -y install epel-release
      yum -y install wget screen rsync vim-enhanced bind-utils net-tools bash-completion bash-completion-extras

      # Install Salt repo
      yum install -y https://repo.saltstack.com/yum/redhat/salt-repo-2016.11-2.el7.noarch.rpm

      # Expire YUM cache
      yum clean expire-cache

      # Install Salt
      yum install -y salt salt-minion-0:2016.11.9-2.el7.noarch

      # install salt config files for master
      cat /vagrant/etc/minion > /etc/salt/minion

      # Set local hostname
      hostnamectl set-hostname minion#{i}.localdev

      # Set Salt Minion to start at reboot
      systemctl enable salt-minion.service

      # Start Salt Minion service
      systemctl start salt-minion.service

      # key should be auto-accepted on master at this point!

    EOF
  end
end
  
end
